// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package core

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

const GUIDiWebAuthenticationCoreManagerStatics string = "6aca7c92-a581-4479-9c10-752eff44fd34"
const SignatureiWebAuthenticationCoreManagerStatics string = "{6aca7c92-a581-4479-9c10-752eff44fd34}"

type iWebAuthenticationCoreManagerStatics struct {
	ole.IInspectable
}

type iWebAuthenticationCoreManagerStaticsVtbl struct {
	ole.IInspectableVtbl

	WebAuthenticationCoreManagerGetTokenSilentlyAsync                 uintptr
	WebAuthenticationCoreManagerGetTokenSilentlyWithWebAccountAsync   uintptr
	WebAuthenticationCoreManagerRequestTokenAsync                     uintptr
	WebAuthenticationCoreManagerRequestTokenWithWebAccountAsync       uintptr
	WebAuthenticationCoreManagerFindAccountAsync                      uintptr
	WebAuthenticationCoreManagerFindAccountProviderAsync              uintptr
	WebAuthenticationCoreManagerFindAccountProviderWithAuthorityAsync uintptr
}

func (v *iWebAuthenticationCoreManagerStatics) VTable() *iWebAuthenticationCoreManagerStaticsVtbl {
	return (*iWebAuthenticationCoreManagerStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

func WebAuthenticationCoreManagerGetTokenSilentlyAsync(request *WebTokenRequest) (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Authentication.Web.Core.WebAuthenticationCoreManager", ole.NewGUID(GUIDiWebAuthenticationCoreManagerStatics))
	if err != nil {
		return nil, err
	}
	v := (*iWebAuthenticationCoreManagerStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().WebAuthenticationCoreManagerGetTokenSilentlyAsync,
		uintptr(unsafe.Pointer(v)),       // this
		uintptr(unsafe.Pointer(request)), // in WebTokenRequest
		uintptr(unsafe.Pointer(&out)),    // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func WebAuthenticationCoreManagerFindAccountProviderAsync(webAccountProviderId string) (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Authentication.Web.Core.WebAuthenticationCoreManager", ole.NewGUID(GUIDiWebAuthenticationCoreManagerStatics))
	if err != nil {
		return nil, err
	}
	v := (*iWebAuthenticationCoreManagerStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	webAccountProviderIdHStr, err := ole.NewHString(webAccountProviderId)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().WebAuthenticationCoreManagerFindAccountProviderAsync,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(webAccountProviderIdHStr), // in string
		uintptr(unsafe.Pointer(&out)),     // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
