// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package core

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureWebProviderError string = "rc(Windows.Security.Authentication.Web.Core.WebProviderError;{db191bb1-50c5-4809-8dca-09c99410245c})"

type WebProviderError struct {
	ole.IUnknown
}

func (impl *WebProviderError) GetErrorCode() (uint32, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiWebProviderError))
	defer itf.Release()
	v := (*iWebProviderError)(unsafe.Pointer(itf))
	return v.GetErrorCode()
}

func (impl *WebProviderError) GetErrorMessage() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiWebProviderError))
	defer itf.Release()
	v := (*iWebProviderError)(unsafe.Pointer(itf))
	return v.GetErrorMessage()
}

const GUIDiWebProviderError string = "db191bb1-50c5-4809-8dca-09c99410245c"
const SignatureiWebProviderError string = "{db191bb1-50c5-4809-8dca-09c99410245c}"

type iWebProviderError struct {
	ole.IInspectable
}

type iWebProviderErrorVtbl struct {
	ole.IInspectableVtbl

	GetErrorCode    uintptr
	GetErrorMessage uintptr
	GetProperties   uintptr
}

func (v *iWebProviderError) VTable() *iWebProviderErrorVtbl {
	return (*iWebProviderErrorVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iWebProviderError) GetErrorCode() (uint32, error) {
	var out uint32
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetErrorCode,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out uint32
	)

	if hr != 0 {
		return 0, ole.NewError(hr)
	}

	return out, nil
}

func (v *iWebProviderError) GetErrorMessage() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetErrorMessage,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

const GUIDiWebProviderErrorFactory string = "e3c40a2d-89ef-4e37-847f-a8b9d5a32910"
const SignatureiWebProviderErrorFactory string = "{e3c40a2d-89ef-4e37-847f-a8b9d5a32910}"

type iWebProviderErrorFactory struct {
	ole.IInspectable
}

type iWebProviderErrorFactoryVtbl struct {
	ole.IInspectableVtbl

	WebProviderErrorCreate uintptr
}

func (v *iWebProviderErrorFactory) VTable() *iWebProviderErrorFactoryVtbl {
	return (*iWebProviderErrorFactoryVtbl)(unsafe.Pointer(v.RawVTable))
}

func WebProviderErrorCreate(errorCode uint32, errorMessage string) (*WebProviderError, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Authentication.Web.Core.WebProviderError", ole.NewGUID(GUIDiWebProviderErrorFactory))
	if err != nil {
		return nil, err
	}
	v := (*iWebProviderErrorFactory)(unsafe.Pointer(inspectable))

	var out *WebProviderError
	errorMessageHStr, err := ole.NewHString(errorMessage)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().WebProviderErrorCreate,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(errorCode),            // in uint32
		uintptr(errorMessageHStr),     // in string
		uintptr(unsafe.Pointer(&out)), // out WebProviderError
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
