// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package core

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation/collections"
)

const SignatureWebTokenRequestResult string = "rc(Windows.Security.Authentication.Web.Core.WebTokenRequestResult;{c12a8305-d1f8-4483-8d54-38fe292784ff})"

type WebTokenRequestResult struct {
	ole.IUnknown
}

func (impl *WebTokenRequestResult) GetResponseData() (*collections.IVectorView, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiWebTokenRequestResult))
	defer itf.Release()
	v := (*iWebTokenRequestResult)(unsafe.Pointer(itf))
	return v.GetResponseData()
}

func (impl *WebTokenRequestResult) GetResponseStatus() (WebTokenRequestStatus, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiWebTokenRequestResult))
	defer itf.Release()
	v := (*iWebTokenRequestResult)(unsafe.Pointer(itf))
	return v.GetResponseStatus()
}

func (impl *WebTokenRequestResult) GetResponseError() (*WebProviderError, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiWebTokenRequestResult))
	defer itf.Release()
	v := (*iWebTokenRequestResult)(unsafe.Pointer(itf))
	return v.GetResponseError()
}

const GUIDiWebTokenRequestResult string = "c12a8305-d1f8-4483-8d54-38fe292784ff"
const SignatureiWebTokenRequestResult string = "{c12a8305-d1f8-4483-8d54-38fe292784ff}"

type iWebTokenRequestResult struct {
	ole.IInspectable
}

type iWebTokenRequestResultVtbl struct {
	ole.IInspectableVtbl

	GetResponseData      uintptr
	GetResponseStatus    uintptr
	GetResponseError     uintptr
	InvalidateCacheAsync uintptr
}

func (v *iWebTokenRequestResult) VTable() *iWebTokenRequestResultVtbl {
	return (*iWebTokenRequestResultVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iWebTokenRequestResult) GetResponseData() (*collections.IVectorView, error) {
	var out *collections.IVectorView
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetResponseData,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out collections.IVectorView
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iWebTokenRequestResult) GetResponseStatus() (WebTokenRequestStatus, error) {
	var out WebTokenRequestStatus
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetResponseStatus,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out WebTokenRequestStatus
	)

	if hr != 0 {
		return WebTokenRequestStatusSuccess, ole.NewError(hr)
	}

	return out, nil
}

func (v *iWebTokenRequestResult) GetResponseError() (*WebProviderError, error) {
	var out *WebProviderError
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetResponseError,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out WebProviderError
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
