// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package core

type WebTokenRequestPromptType int32

const SignatureWebTokenRequestPromptType string = "enum(Windows.Security.Authentication.Web.Core.WebTokenRequestPromptType;i4)"

const (
	WebTokenRequestPromptTypeDefault             WebTokenRequestPromptType = 0
	WebTokenRequestPromptTypeForceAuthentication WebTokenRequestPromptType = 1
)
