// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package core

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureWebTokenResponse string = "rc(Windows.Security.Authentication.Web.Core.WebTokenResponse;{67a7c5ca-83f6-44c6-a3b1-0eb69e41fa8a})"

type WebTokenResponse struct {
	ole.IUnknown
}

func NewWebTokenResponse() (*WebTokenResponse, error) {
	inspectable, err := ole.RoActivateInstance("Windows.Security.Authentication.Web.Core.WebTokenResponse")
	if err != nil {
		return nil, err
	}
	return (*WebTokenResponse)(unsafe.Pointer(inspectable)), nil
}

func (impl *WebTokenResponse) GetToken() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiWebTokenResponse))
	defer itf.Release()
	v := (*iWebTokenResponse)(unsafe.Pointer(itf))
	return v.GetToken()
}

const GUIDiWebTokenResponse string = "67a7c5ca-83f6-44c6-a3b1-0eb69e41fa8a"
const SignatureiWebTokenResponse string = "{67a7c5ca-83f6-44c6-a3b1-0eb69e41fa8a}"

type iWebTokenResponse struct {
	ole.IInspectable
}

type iWebTokenResponseVtbl struct {
	ole.IInspectableVtbl

	GetToken         uintptr
	GetProviderError uintptr
	GetWebAccount    uintptr
	GetProperties    uintptr
}

func (v *iWebTokenResponse) VTable() *iWebTokenResponseVtbl {
	return (*iWebTokenResponseVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iWebTokenResponse) GetToken() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetToken,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}
