// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package core

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/liteldev/LeviLauncher/internal/xbox/winrt/credentials"
)

const SignatureWebTokenRequest string = "rc(Windows.Security.Authentication.Web.Core.WebTokenRequest;{b77b4d68-adcb-4673-b364-0cf7b35caf97})"

type WebTokenRequest struct {
	ole.IUnknown
}

func (impl *WebTokenRequest) GetWebAccountProvider() (*credentials.WebAccountProvider, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiWebTokenRequest))
	defer itf.Release()
	v := (*iWebTokenRequest)(unsafe.Pointer(itf))
	return v.GetWebAccountProvider()
}

func (impl *WebTokenRequest) GetScope() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiWebTokenRequest))
	defer itf.Release()
	v := (*iWebTokenRequest)(unsafe.Pointer(itf))
	return v.GetScope()
}

func (impl *WebTokenRequest) GetClientId() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiWebTokenRequest))
	defer itf.Release()
	v := (*iWebTokenRequest)(unsafe.Pointer(itf))
	return v.GetClientId()
}

func (impl *WebTokenRequest) GetPromptType() (WebTokenRequestPromptType, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiWebTokenRequest))
	defer itf.Release()
	v := (*iWebTokenRequest)(unsafe.Pointer(itf))
	return v.GetPromptType()
}

func (impl *WebTokenRequest) GetCorrelationId() (string, error) {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiWebTokenRequest3))
	defer itf.Release()
	v := (*iWebTokenRequest3)(unsafe.Pointer(itf))
	return v.GetCorrelationId()
}

func (impl *WebTokenRequest) SetCorrelationId(value string) error {
	itf := impl.MustQueryInterface(ole.NewGUID(GUIDiWebTokenRequest3))
	defer itf.Release()
	v := (*iWebTokenRequest3)(unsafe.Pointer(itf))
	return v.SetCorrelationId(value)
}

const GUIDiWebTokenRequest string = "b77b4d68-adcb-4673-b364-0cf7b35caf97"
const SignatureiWebTokenRequest string = "{b77b4d68-adcb-4673-b364-0cf7b35caf97}"

type iWebTokenRequest struct {
	ole.IInspectable
}

type iWebTokenRequestVtbl struct {
	ole.IInspectableVtbl

	GetWebAccountProvider uintptr
	GetScope              uintptr
	GetClientId           uintptr
	GetPromptType         uintptr
	GetProperties         uintptr
}

func (v *iWebTokenRequest) VTable() *iWebTokenRequestVtbl {
	return (*iWebTokenRequestVtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iWebTokenRequest) GetWebAccountProvider() (*credentials.WebAccountProvider, error) {
	var out *credentials.WebAccountProvider
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetWebAccountProvider,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out credentials.WebAccountProvider
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func (v *iWebTokenRequest) GetScope() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetScope,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iWebTokenRequest) GetClientId() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetClientId,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iWebTokenRequest) GetPromptType() (WebTokenRequestPromptType, error) {
	var out WebTokenRequestPromptType
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetPromptType,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out WebTokenRequestPromptType
	)

	if hr != 0 {
		return WebTokenRequestPromptTypeDefault, ole.NewError(hr)
	}

	return out, nil
}

const GUIDiWebTokenRequest2 string = "d700c079-30c8-4397-9654-961c3be8b855"
const SignatureiWebTokenRequest2 string = "{d700c079-30c8-4397-9654-961c3be8b855}"

type iWebTokenRequest2 struct {
	ole.IInspectable
}

type iWebTokenRequest2Vtbl struct {
	ole.IInspectableVtbl

	GetAppProperties uintptr
}

func (v *iWebTokenRequest2) VTable() *iWebTokenRequest2Vtbl {
	return (*iWebTokenRequest2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiWebTokenRequest3 string = "5a755b51-3bb1-41a5-a63d-90bc32c7db9a"
const SignatureiWebTokenRequest3 string = "{5a755b51-3bb1-41a5-a63d-90bc32c7db9a}"

type iWebTokenRequest3 struct {
	ole.IInspectable
}

type iWebTokenRequest3Vtbl struct {
	ole.IInspectableVtbl

	GetCorrelationId uintptr
	SetCorrelationId uintptr
}

func (v *iWebTokenRequest3) VTable() *iWebTokenRequest3Vtbl {
	return (*iWebTokenRequest3Vtbl)(unsafe.Pointer(v.RawVTable))
}

func (v *iWebTokenRequest3) GetCorrelationId() (string, error) {
	var outHStr ole.HString
	hr, _, _ := syscall.SyscallN(
		v.VTable().GetCorrelationId,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(&outHStr)), // out string
	)

	if hr != 0 {
		return "", ole.NewError(hr)
	}

	out := outHStr.String()
	ole.DeleteHString(outHStr)
	return out, nil
}

func (v *iWebTokenRequest3) SetCorrelationId(value string) error {
	valueHStr, err := ole.NewHString(value)
	if err != nil {
		return err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().SetCorrelationId,
		uintptr(unsafe.Pointer(v)), // this
		uintptr(valueHStr),         // in string
	)

	if hr != 0 {
		return ole.NewError(hr)
	}

	return nil
}

const GUIDiWebTokenRequestFactory string = "6cf2141c-0ff0-4c67-b84f-99ddbe4a72c9"
const SignatureiWebTokenRequestFactory string = "{6cf2141c-0ff0-4c67-b84f-99ddbe4a72c9}"

type iWebTokenRequestFactory struct {
	ole.IInspectable
}

type iWebTokenRequestFactoryVtbl struct {
	ole.IInspectableVtbl

	WebTokenRequestCreate               uintptr
	WebTokenRequestCreateWithPromptType uintptr
	WebTokenRequestCreateWithProvider   uintptr
	WebTokenRequestCreateWithScope      uintptr
}

func (v *iWebTokenRequestFactory) VTable() *iWebTokenRequestFactoryVtbl {
	return (*iWebTokenRequestFactoryVtbl)(unsafe.Pointer(v.RawVTable))
}

func WebTokenRequestCreate(provider *credentials.WebAccountProvider, scope string, clientId string) (*WebTokenRequest, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Authentication.Web.Core.WebTokenRequest", ole.NewGUID(GUIDiWebTokenRequestFactory))
	if err != nil {
		return nil, err
	}
	v := (*iWebTokenRequestFactory)(unsafe.Pointer(inspectable))

	var out *WebTokenRequest
	scopeHStr, err := ole.NewHString(scope)
	if err != nil {
		return nil, err
	}
	clientIdHStr, err := ole.NewHString(clientId)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().WebTokenRequestCreate,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(provider)), // in credentials.WebAccountProvider
		uintptr(scopeHStr),                // in string
		uintptr(clientIdHStr),             // in string
		uintptr(unsafe.Pointer(&out)),     // out WebTokenRequest
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func WebTokenRequestCreateWithPromptType(provider *credentials.WebAccountProvider, scope string, clientId string, promptType WebTokenRequestPromptType) (*WebTokenRequest, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Authentication.Web.Core.WebTokenRequest", ole.NewGUID(GUIDiWebTokenRequestFactory))
	if err != nil {
		return nil, err
	}
	v := (*iWebTokenRequestFactory)(unsafe.Pointer(inspectable))

	var out *WebTokenRequest
	scopeHStr, err := ole.NewHString(scope)
	if err != nil {
		return nil, err
	}
	clientIdHStr, err := ole.NewHString(clientId)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().WebTokenRequestCreateWithPromptType,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(provider)), // in credentials.WebAccountProvider
		uintptr(scopeHStr),                // in string
		uintptr(clientIdHStr),             // in string
		uintptr(promptType),               // in WebTokenRequestPromptType
		uintptr(unsafe.Pointer(&out)),     // out WebTokenRequest
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func WebTokenRequestCreateWithProvider(provider *credentials.WebAccountProvider) (*WebTokenRequest, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Authentication.Web.Core.WebTokenRequest", ole.NewGUID(GUIDiWebTokenRequestFactory))
	if err != nil {
		return nil, err
	}
	v := (*iWebTokenRequestFactory)(unsafe.Pointer(inspectable))

	var out *WebTokenRequest
	hr, _, _ := syscall.SyscallN(
		v.VTable().WebTokenRequestCreateWithProvider,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(provider)), // in credentials.WebAccountProvider
		uintptr(unsafe.Pointer(&out)),     // out WebTokenRequest
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

func WebTokenRequestCreateWithScope(provider *credentials.WebAccountProvider, scope string) (*WebTokenRequest, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Authentication.Web.Core.WebTokenRequest", ole.NewGUID(GUIDiWebTokenRequestFactory))
	if err != nil {
		return nil, err
	}
	v := (*iWebTokenRequestFactory)(unsafe.Pointer(inspectable))

	var out *WebTokenRequest
	scopeHStr, err := ole.NewHString(scope)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().WebTokenRequestCreateWithScope,
		uintptr(unsafe.Pointer(v)),        // this
		uintptr(unsafe.Pointer(provider)), // in credentials.WebAccountProvider
		uintptr(scopeHStr),                // in string
		uintptr(unsafe.Pointer(&out)),     // out WebTokenRequest
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
