// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package core

type WebTokenRequestStatus int32

const SignatureWebTokenRequestStatus string = "enum(Windows.Security.Authentication.Web.Core.WebTokenRequestStatus;i4)"

const (
	WebTokenRequestStatusSuccess                     WebTokenRequestStatus = 0
	WebTokenRequestStatusUserCancel                  WebTokenRequestStatus = 1
	WebTokenRequestStatusAccountSwitch               WebTokenRequestStatus = 2
	WebTokenRequestStatusUserInteractionRequired     WebTokenRequestStatus = 3
	WebTokenRequestStatusAccountProviderNotAvailable WebTokenRequestStatus = 4
	WebTokenRequestStatusProviderError               WebTokenRequestStatus = 5
)
