// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all
package credentials

import (
	"unsafe"

	"github.com/go-ole/go-ole"
)

const SignatureWebAccountProvider string = "rc(Windows.Security.Credentials.WebAccountProvider;{29dcc8c3-7ab9-4a7c-a336-b942f9dbf7c7})"

type WebAccountProvider struct {
	ole.IUnknown
}

const GUIDiWebAccountProvider string = "29dcc8c3-7ab9-4a7c-a336-b942f9dbf7c7"
const SignatureiWebAccountProvider string = "{29dcc8c3-7ab9-4a7c-a336-b942f9dbf7c7}"

type iWebAccountProvider struct {
	ole.IInspectable
}

type iWebAccountProviderVtbl struct {
	ole.IInspectableVtbl

	GetId          uintptr
	GetDisplayName uintptr
	GetIconUri     uintptr
}

func (v *iWebAccountProvider) VTable() *iWebAccountProviderVtbl {
	return (*iWebAccountProviderVtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiWebAccountProvider2 string = "4a01eb05-4e42-41d4-b518-e008a5163614"
const SignatureiWebAccountProvider2 string = "{4a01eb05-4e42-41d4-b518-e008a5163614}"

type iWebAccountProvider2 struct {
	ole.IInspectable
}

type iWebAccountProvider2Vtbl struct {
	ole.IInspectableVtbl

	GetDisplayPurpose uintptr
	GetAuthority      uintptr
}

func (v *iWebAccountProvider2) VTable() *iWebAccountProvider2Vtbl {
	return (*iWebAccountProvider2Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiWebAccountProvider3 string = "da1c518b-970d-4d49-825c-f2706f8ca7fe"
const SignatureiWebAccountProvider3 string = "{da1c518b-970d-4d49-825c-f2706f8ca7fe}"

type iWebAccountProvider3 struct {
	ole.IInspectable
}

type iWebAccountProvider3Vtbl struct {
	ole.IInspectableVtbl

	GetUser uintptr
}

func (v *iWebAccountProvider3) VTable() *iWebAccountProvider3Vtbl {
	return (*iWebAccountProvider3Vtbl)(unsafe.Pointer(v.RawVTable))
}

const GUIDiWebAccountProvider4 string = "718fd8db-e796-4210-b74e-84d29894b080"
const SignatureiWebAccountProvider4 string = "{718fd8db-e796-4210-b74e-84d29894b080}"

type iWebAccountProvider4 struct {
	ole.IInspectable
}

type iWebAccountProvider4Vtbl struct {
	ole.IInspectableVtbl

	GetIsSystemProvider uintptr
}

func (v *iWebAccountProvider4) VTable() *iWebAccountProvider4Vtbl {
	return (*iWebAccountProvider4Vtbl)(unsafe.Pointer(v.RawVTable))
}
